www/forums/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from forums.views import CategoryListView, ForumDetailView, TopicDetailView, TopicCreateView, \
    PostCreateView


urlpatterns = patterns('',
                       url(r'^$', CategoryListView.as_view(), name='overview'),
                       url(r'^(?P<pk>\d+)/$', ForumDetailView.as_view(), name='forum'),
                       url(r'^(?P<forum_id>\d+)/create/$',
                           login_required(TopicCreateView.as_view()),
                           name='topic_create'),
                       url(r'^topic/(?P<pk>\d+)/$', TopicDetailView.as_view(), name='topic'),
                       url(r'^topic/(?P<pk>\d+)/create/$', login_required(PostCreateView.as_view()),
                           name='post_create'),
)

www/robots/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('robots.views',
    url(r'^$', 'rules_list', name='robots_rule_list'),
)

www/www/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib.sitemaps import FlatPageSitemap
from django.conf import settings

from django.contrib import admin

admin.autodiscover()

from news.sitemap import NewsSitemap
from article.sitemap import ArticleSitemap
from forums.sitemap import ForumSitemap, TopicSitemap

sitemaps = {
    'flatpages': FlatPageSitemap,
    'news': NewsSitemap,
    'article': ArticleSitemap,
    'forums': ForumSitemap,
    'topic': TopicSitemap,
}

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^admin_tools/', include('admin_tools.urls')),

                       url(r'^ckeditor/', include('ckeditor.urls')),
                       url(r'^captcha/', include('captcha.urls')),

                       url(r'^article/', include('article.urls')),
                       url(r'^contacts/', include('feedback.urls')),
                       url(r'^question/', include('questionanswer.urls')),
                       url(r'^news/', include('news.urls')),
                       url(r'^video/', include('video.urls')),
                       url(r'^forums/', include('forums.urls',  namespace='forums')),

                       url(r'^robots\.txt$', include('robots.urls')),
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
                           {'sitemaps': sitemaps}),

                       url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.STATIC_ROOT}),
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),
)

www/forums/models.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Category(models.Model):
    name = models.CharField(_("Name"), max_length=255, unique=True)
    position = models.IntegerField(_("Position"), default=0)

    class Meta:
        verbose_name = u'категория'
        verbose_name_plural = u'категории'
        ordering = ['position']

    def __unicode__(self):
        return self.name


class Forum(models.Model):
    category = models.ForeignKey(Category, related_name='forums', verbose_name=u'категория')
    name = models.CharField(_("Name"), max_length=255)
    position = models.IntegerField(_("Position"), default=0)
    description = models.TextField(_("Description"), blank=True)
    is_closed = models.BooleanField(_("Is closed"), default=False)

    class Meta:
        verbose_name = u'форум'
        verbose_name_plural = u'форумы'
        ordering = ['position']

    def get_latest_topic(self):
        if self.topics.count() > 0:
            return self.topics.all()[0]
        return None

    def get_latest_poster(self):
        latest_topic = self.get_latest_topic()
        if latest_topic:
            return latest_topic.last_post.user.username
        return '-'

    def count_topics(self):
        return self.topics.count()

    def count_posts(self):
        count = 0
        for topic in self.topics.all():
            count += topic.count_posts()
        return count

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('forums:forum', (), {'pk': self.id})


class Topic(models.Model):
    forum = models.ForeignKey(Forum, related_name='topics', verbose_name=u'форум')
    name = models.CharField(_("Name"), max_length=255)
    last_post = models.ForeignKey('Post', verbose_name=_("Last post"),
                                  related_name='forum_last_post', blank=True, null=True)

    class Meta:
        verbose_name = u'топик'
        verbose_name_plural = u'топики'
        ordering = ['-last_post__created']

    def count_posts(self):
        return self.posts.count()

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('forums:topic', (), {'pk': self.id})


class Post(models.Model):
    topic = models.ForeignKey(Topic, related_name='posts', verbose_name=u'топик')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='forum_posts')
    created = models.DateTimeField(_("Created"), auto_now_add=True)
    updated = models.DateTimeField(_("Updated"), auto_now=True)
    body = models.TextField(_("Body"))

    class Meta:
        verbose_name = u'пост'
        verbose_name_plural = u'посты'
        ordering = ['created']

    def __unicode__(self):
        return self.body

www/victoria/models.py
# -*- coding: utf-8 -*-

www/forums/forms.py
# -*- coding: utf-8 -*-
from django import forms


class TopicCreateForm(forms.Form):
    topic = forms.CharField(label=u"Топик", min_length=3)
    message = forms.CharField(label=u"Сообщение", min_length=3, widget=forms.Textarea())


class PostCreateForm(forms.Form):
    message = forms.CharField(label=u"Сообщение", min_length=3, widget=forms.Textarea())

www/forums/views.py
from django.views.generic import ListView, DetailView, FormView
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

from forums.forms import TopicCreateForm, PostCreateForm
from forums.models import Category, Topic, Forum, Post

####################################################################################################
####################################################################################################


class ForumMixin(object):
    def get_context_data(self, **kwargs):
        """
        Mixin for forum active menu
        """
        context = super(ForumMixin, self).get_context_data(**kwargs)
        context.update({'active': 'forum'})
        return context

####################################################################################################
####################################################################################################


class CategoryListView(ForumMixin, ListView):
    model = Category


class ForumDetailView(ForumMixin, DetailView):
    model = Forum


class TopicDetailView(ForumMixin, DetailView):
    model = Topic


class TopicCreateView(ForumMixin, FormView):
    template_name = 'forums/topic_create.html'
    form_class = TopicCreateForm

    def dispatch(self, request, *args, **kwargs):
        self.forum = Forum.objects.get(id=kwargs.get('forum_id', None))
        if self.forum.is_closed and not request.user.is_staff:
            messages.error(request, _("You do not have the permissions to create a topic."))
            return HttpResponseRedirect(reverse_lazy('forums:forum', args=[self.forum.id]))
        return super(TopicCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        topic_name = form.cleaned_data['topic']
        post_body = form.cleaned_data['message']
        user = self.request.user

        topic = Topic(forum=self.forum, name=topic_name)
        topic.save()
        post = Post(topic=topic, body=post_body, user=user)
        post.save()
        topic.last_post = post
        topic.save()

        self.success_url = reverse('forums:topic', args=[topic.id])

        return super(TopicCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(TopicCreateView, self).get_context_data(**kwargs)
        context['forum'] = Forum.objects.get(id=self.kwargs.get('forum_id', None))
        return context


class PostCreateView(ForumMixin, FormView):
    template_name = 'forums/post_create.html'
    form_class = PostCreateForm

    def dispatch(self, request, *args, **kwargs):
        self.topic = Topic.objects.get(id=kwargs.get('pk', None))
        if self.topic.forum.is_closed and not request.user.is_staff:
            messages.error(request, _("You do not have the permissions to create a topic."))
            return HttpResponseRedirect(reverse_lazy('forums:forum', args=[self.topic.forum.id]))
        return super(PostCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        body = form.cleaned_data['message']
        user = self.request.user

        post = Post(topic=self.topic, body=body, user=user)
        post.save()
        post.topic.last_post = post
        post.topic.save()

        self.success_url = reverse('forums:topic', args=[self.topic.id])

        return super(PostCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PostCreateView, self).get_context_data(**kwargs)
        context['topic'] = Topic.objects.get(id=self.kwargs.get('pk', None))
        return context

www/victoria/templates/forums/category_list.html
{% extends "default.html" %}

{% load i18n %}

{% block title %}
{% trans "Forums" %} - {{block.super}}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="active">{% trans "Forums" %}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
  <h1>{% trans "Forums" %}</h1>
</div>
<table class="table">
  {% for category in category_list %}
  <thead>
    <tr>
      <th colspan="2"><a name="{{category.id}}">{{category.name}}</a></th>
      <td>{% trans "Last Poster" %}</td>
      <td>{% trans "Topics" %}</td>
      <td>{% trans "Posts" %}</td>
    </tr>
  </thead>
  <tbody>
  {% for forum in category.forums.all %}
  <tr>
    <td style="width: 14px;"><i class="icon-circle-arrow-right" style="margin-top: 1px;"></i></td>
    <td style="width: 70%;">
      <a href="{% url 'forums:forum' forum.id %}">{{forum.name}}</a>
    </td>
    <td>{{forum.get_latest_poster}}</td>
    <td>{{forum.count_topics}}</td>
    <td>{{forum.count_posts}}</td>
  </tr>
  {% endfor %}
  </tbody>
  {% endfor %}
</table>
{% endblock %}

www/victoria/templates/forums/forum_detail.html
{% extends "default.html" %}

{% load i18n %}

{% block title %}
{% trans "Forums" %} - {{block.super}}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'forums:overview' %}">{% trans "Forums" %}</a></li>
  <li><a href="{% url 'forums:overview' %}#{{forum.category.id}}">{{forum.category.name}}</a> </li>
  <li class="active">{{forum.name}}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
  <h1>{% trans "Forums" %}</h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th colspan="2">{% trans "Topics" %}</th>
      <td>{% trans "Last Poster" %}</td>
      <td>{% trans "Replies" %}</td>
      <td>{% trans "Views" %}</td>
    </tr>
  </thead>
  <tbody>
  {% for topic in forum.topics.all %}
  <tr>
    <td style="width: 14px;"><i class="icon-circle-arrow-right" style="margin-top: 1px;"></i></td>
    <td style="width: 70%;">
      <a href="{% url 'forums:topic' topic.id %}">{{topic.name}}</a>
    </td>
    <td>{{topic.last_post.user.username}}</td>
    <td>{{topic.count_posts}}</td>
    <td>0</td>
  </tr>
  {% empty %}
  {% if forum.is_closed %}
  <tr>
    <td colspan="5">{% trans "No topics in this forum, only admins can create and post here." %}</td>
  </tr>
  {% else %}
  <tr>
    <td colspan="5">{% trans "No topics in this forum, create one :)" %}</td>
  </tr>
  {% endif %}
  {% endfor %}
  </tbody>
</table>
{% if not forum.is_closed or user.is_staff %}
<p><a href="{% url 'forums:topic_create' forum.id %}" class="btn btn-primary">{% trans "Create topic" %}</a></p>
{% endif %}
{% endblock %}

www/victoria/templates/forums/post_create.html
{% extends "default.html" %}

{% load i18n %}

{% block title %}
{% trans "Forums" %} - {{block.super}}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'forums:overview' %}">{% trans "Forums" %}</a></li>
  <li><a href="{% url 'forums:overview' %}#{{topic.forum.category.id}}">{{topic.forum.category.name}}</a></li>
  <li><a href="{% url 'forums:forum' topic.forum.id %}">{{topic.forum.name}}</a></li>
  <li><a href="{% url 'forums:topic' topic.id %}">{{topic.name}}</a></li>
  <li class="active">{% trans "Create post" %}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
  <h1>{% trans "Forums" %}</h1>
</div>
<div class="row">
  <div class="col-md-3">
    <div class="thumbnail pull-left" style="margin-right: 15px;">
      <img src="http://placehold.it/64x64" alt="avatar">
    </div>
    <div>
      <p>{{user.username}}</p>
    </div>
  </div>
  <div class="col-md-9">
    <form method="post" action="{% url 'forums:post_create' topic.id %}">
      {% csrf_token %}
      {% include "forms.html" %}
      <p><input type="submit" class="btn btn-primary" value="{% trans "Create post" %}"></p>
    </form>
  </div>
</div>
{% endblock %}

www/victoria/templates/forums/topic_create.html
{% extends "default.html" %}

{% load i18n %}

{% block title %}
{% trans "Forums" %} - {{block.super}}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'forums:overview' %}">{% trans "Forums" %}</a></li>
  <li><a href="{% url 'forums:overview' %}#{{forum.category.id}}">{{forum.category.name}}</a> </li>
  <li><a href="{% url 'forums:forum' forum.id %}">{{forum.name}}</a></li>
  <li class="active">{% trans "Create topic" %}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
  <h1>{% trans "Forums" %}</h1>
</div>
<div class="row">
  <div class="col-md-3">
    <div class="thumbnail pull-left" style="margin-right: 15px;">
      <img src="http://placehold.it/64x64" alt="avatar">
    </div>
    <div>
      <p>{{user.username}}</p>
    </div>
  </div>
  <div class="col-md-9">
    <form method="post" action="{% url 'forums:topic_create' forum.id %}">
      {% csrf_token %}
      {% include "forms.html" %}
      <p><input type="submit" class="btn btn-primary" value="{% trans "Create topic" %}"></p>
    </form>
  </div>
</div>
{% endblock %}

www/victoria/templates/forums/topic_detail.html
{% extends "default.html" %}

{% load i18n %}

{% block title %}
{% trans "Forums" %} - {{block.super}}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'forums:overview' %}">{% trans "Forums" %}</a></li>
  <li><a href="{% url 'forums:overview' %}#{{topic.forum.category.id}}">{{topic.forum.category.name}}</a></li>
  <li><a href="{% url 'forums:forum' topic.forum.id %}">{{topic.forum.name}}</a></li>
  <li class="active">{{topic.name}}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
  <h1>{% trans "Forums" %}</h1>
</div>
{% for post in topic.posts.all %}
<div class="row">
  <div class="span3">
    <div class="thumbnail pull-left" style="margin-right: 15px;">
      <img src="http://placehold.it/64x64" alt="avatar">
    </div>
    <div>
      <p>{{post.user.username}}</p>
    </div>
  </div>
  <div class="span7">
    <div>
      {{post.body|linebreaks}}
    </div>
    <div style="clear: both;"></div>
  </div>
  <div class="span2">
    <p class="pull-right"><small><a href="#{{forloop.counter}}" name="{{forloop.counter}}">#{{forloop.counter}}</a></small></p>
    <p class="pull-right"><small>{{post.created}}</small></p>
  </div>
</div>
<hr>
{% endfor %}
<div class="row">
  <div class="span12">
    {% if not topic.forum.is_closed or user.is_staff %}
    <p><a href="{% url 'forums:post_create' topic.id %}" class="btn btn-primary">{% trans "Create post" %}</a></p>
    {% else %}
    <p>{% trans "This forum is closed, only admins can create and post here." %}
    {% endif %}
  </div>
</div>
{% endblock %}